### ISSUE TITLE
Extract info on mobile browsers

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/web-roadmaps#13]
right now the implementation data is for "browsers" without distinction; for the mobile roadmap, we probably want to get info specific to Chrome Android, as well as on the Android browser. Ideally, also add more browsers popular on mobile (Samsung Internet, etc)

**Comment by tidoust** [comment]
Some additional notes: we have some info already from Can I Use. The main difficulty is finding a good way to present it.

Before listing all mobile browsers, we should also study the data to see if there are major differences for the features we reference between the desktop version and the mobile version of a given browser (e.g. between Chrome for desktop and Chrome for Android). If there is a very good overlap, we should consider merging the two informations into the same icon.

**Comment by jpmedley** [comment]
For Chromium, the versions to consider are Chrome for Android, Android webview, Opera for Android, and Samsung Browser. Opera generally keeps feature parity with Chromium, but not always. Their version number is 13 behind ours. So Chrome 63 = Opera 50.

The real concern is that desktop, Android, and Android webview generally have feature parity. Once in a blue moon they do not. Here's an extreme example: https://www.chromestatus.com/features/6338383617982464

**Comment by xfq** [comment]
The HTML Media Capture feature is supported in Chrome on Android and iOS Safari: https://caniuse.com/#feat=html-media-capture

But from https://w3c.github.io/web-roadmaps/mobile/media.html no implementation is listed at all. I think the reason is we only use the implementation data from desktop browsers currently.

**Comment by tidoust** [comment]
Roadmap pages now display basic information about support in mobile browsers, using badges overlaid on top of browser icons. Browsers that are being tracked are:
- Chrome for Android (possible sources: Chrome Platform Status and Can I Use)
- Firefox for Android (possible source: Can I Use)
- Opera for Android (possible sources: Chrome Platform Status and Can I Use)
- Samsung Internet (possible source: Can I Use, that info does not explicitly appear in Chrome Platform Status data)
- Safari for iOS (possible source: Can I Use, that info does not explicitly appear in Webkit status data)
- QQ Browser for Android (possible source: Can I Use)
- UC Browser for Android (possible source: Can I Use)

Only the "main" codebases are shown by default, but the other ones can be displayed through a filtering menu in the implementation column header.

I've ignored the Android WebView for now but it could be added later on if that feels needed. Also did not try to list the Android Browser, as I believe Chrome for Android has now replaced it.

The roadmap pages do not try to convey the version in which a feature was added, just the fact that a particular feature is supported or in development. Badges show whether the feature is supported in the desktop variant only, in the mobile variant only (I'll add some text in an "About" page to explain that "mobile" means Android for most browsers and iOS for Safari: stuff like "Firefox for iOS" are a completely different beast), or both on desktop and mobile, which should be the most common situation.

When Chrome Platform status reports that a feature is in development, it does not say if it's only for a particular variant. The code assumes that the feature is in development in the desktop and mobile versions. This should be mostly correct for recent features.

I'm closing this issue for now. Feel free to suggest corrections and improvements to the current system, either here or as a separate issue.

**Comment by tidoust** [comment]
@jpmedley, you noted that:

> Opera generally keeps feature parity with Chromium, but not always. Their version number is 13 behind ours. So Chrome 63 = Opera 50

That seems valid for Opera for Desktop, but not for Opera for Android. For instance, the [current version of Opera for Android](https://play.google.com/store/apps/details?id=com.opera.browser) is 45, and says it is based on Chromium 61, so that's "version - 16".

The information in [`features.json`](https://www.chromestatus/features.json) seems to apply the "version - 13" rule thoroughly, which means it is too "pessimistic" for Opera for Android: Chromium 61 features should already ship in Opera for Android, but the file says they will only be supported in Opera for Android starting in version 48, which does not exist yet.
