### ISSUE TITLE
About the WAI-ARIA data files

### ISSUE THREAD

**Issue by xfq** [w3c/web-roadmaps#203]
Currently, there are two JSON files for WAI-ARIA: `wai-aria.json` and `wai-aria11.json`. The "TR" value for them are https://www.w3.org/TR/wai-aria/ and https://www.w3.org/TR/wai-aria-1.1/ respectively. Although both of them currently contain the ARIA 1.1 spec, the spec name in http://www.w3.org/2002/01/tr-automation/tr.rdf seems to be "Accessible Rich Internet Applications (WAI-ARIA) 1.0" (instead of 1.1).

What should we do? Should we merge the two files?

**Comment by tidoust** [comment]
I should have linked to `wai-aria11` and we should indeed drop the `wai-aria.json` file. If a roadmap needs to link to v1.0, we'll need to create a new file with the `wai-aria-1.0` shortname.

It's interesting that `tr.rdf` treats the `wai-aria` shortname as a synonym to version 1.0 and not as an alias to `wai-aria-1.1`. Is that intended, @deniak?

**Comment by deniak** [comment]
> It's interesting that `tr.rdf` treats the `wai-aria` shortname as a synonym to version 1.0 and not as an alias to `wai-aria-1.1`. Is that intended, @deniak?

Yes, because that's the metadata available in https://www.w3.org/TR/2014/REC-wai-aria-20140320/. It's a recurrent issue. People keep using shortnames and shortlinks to identify specifications but they can change or point to another specifications.
With the new versioning scheme, we allow WGs to decide where the shortlink without the version number should point to but it doesn't change the metadata associated with a document.

**Comment by tidoust** [comment]
Thanks, @deniak, the net result is slightly confusing but I see how that file gets created and that makes sense... I guess that, ideally, the published WAI-ARIA 1.1 spec should have also linked back to https://www.w3.org/TR/wai-aria/ so that the metadata would also contain a `doc:versionOf` property for WAI-ARIA 1.1 that targets that shortname. Anyway...
