### ISSUE TITLE
Spatial data on the Web technology roadmap

### ISSUE THREAD

**Issue by prushforth** [w3c/web-roadmaps#303]
@tidoust  On WICG, there is a category for Web mapping that may be useful: https://discourse.wicg.io/c/web-mapping to capture more discussion about spatial data on the web.  Just a suggestion.

**Comment by prushforth** [comment]
Also, the link that says "We are on github" leads to this repository, rather than the SDW repo.  Is that intentional?

**Comment by tidoust** [comment]
Good point about the Web mapping category, I updated the roadmap accordingly to point users to that.

The link to this repo instead of to the `w3c/sdw` repo is more intended: for practical reasons (the tool that generates the roadmap from the source files requires it), the contents of the roadmap need to remain in this repo, and it seems better to redirect users to a place where they can actually see the source code, rather than to a repo that does not have it. Granted, that's not a perfect setting.
