### ISSUE TITLE
Mention User-Agent Client Hints

### ISSUE THREAD

**Issue by xfq** [w3c/web-roadmaps#454]
It aims to reduce passive fingerprinting surface exposed by the `User-Agent` header.

* Spec: https://wicg.github.io/ua-client-hints/
* Chrome Platform Status: https://www.chromestatus.com/feature/5995832180473856

**Comment by xfq** [comment]
Should we add this to Security and Privacy or Device Adaptation?

**Comment by tidoust** [comment]
Device Memory is mentioned in Device Adaptation, so it makes sense to mention User-Agent Clients Hints there as well.

Thinking out loud, it might make sense to add a paragraph in Security and Privacy that talks about specifications specifically targeted at exposing client capabilities. These specifications need to strike a balance between preserving privacy and exposing fine-grained capabilities. Such a paragraph should include User-Agent Client Hints, Device Memory, Media Capabilities and probably a few others. The problem is that we could probably include lots of specifications, since most specs that expose some new feature need to deal with privacy preserving issues one way or the other. Said differently, if we add User-Agent Client Hints to security and privacy, we should add other specs there as well.
